import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Providers
import { ProgressProvider } from "src/providers/progress"; 
import { ModeProvider } from "src/providers/mode";
import { BfProvider } from "src/providers/bibframe";
import { AlertProvider } from "src/providers/alerts";

import Providers from "src/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <ProgressProvider>
        <ModeProvider>
          <BfProvider>
            <AlertProvider>
              <body className={inter.className}>
                <Providers />
                {children}
              </body>
            </AlertProvider>
          </BfProvider>
        </ModeProvider>
      </ProgressProvider>
    </html>
  );
}
